spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:mysql://localhost:3306/finwiz
    username: root
    password: pass@word1

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      naming-strategy: org.hibernate.cfg.ImproveNamingStrategy
      ddl-auto: update
    show-sql: true

server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
